# Generated by Django 3.2.8 on 2021-10-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_aviso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aviso',
        ),
        migrations.DeleteModel(
            name='Refrigerante',
        ),
    ]
